try:
  raise Exception('HiThere')
except Exception as errorMessage:
  print(errorMessage)
